### ISSUE TITLE
Encountering 'Requires run access to "<command>"' when trying to run commands that are allowed in gauntlet.toml

### ISSUE THREAD

**Issue by cswimr** [project-gauntlet/gauntlet#28]
Title pretty much explains it. I'm trying to use the [deno-open](https://jsr.io/@opensrc/deno-open) package from  JSR, and that executes `xdg-open` on linux. [Here's the codebase](https://www.coastalcommits.com/cswimr/gauntlet-cswimr-plugins/src/branch/tailwindcss), and here's the console output:
```ts
[4:42:41 PM] Change detected. Reloading...
[4:42:43 PM] Reloaded in 2459ms
[4:43:43 PM] Rejected promise PromiseRejectionEvent {
[4:43:43 PM]   bubbles: false,
[4:43:43 PM]   cancelable: true,
[4:43:43 PM]   composed: false,
[4:43:43 PM]   currentTarget: Window {},
[4:43:43 PM]   defaultPrevented: true,
[4:43:43 PM]   eventPhase: 2,
[4:43:43 PM]   srcElement: null,
[4:43:43 PM]   target: Window {},
[4:43:43 PM]   returnValue: false,
[4:43:43 PM]   timeStamp: 0,
[4:43:43 PM]   type: "unhandledrejection",
[4:43:43 PM]   promise: Promise {
[4:43:43 PM]     <rejected> Error: Requires run access to "xdg-open", run again with the --allow-run flag
[4:43:43 PM]     at spawnChildInner (ext:runtime/40_process.js:184:17)
[4:43:43 PM]     at spawn (ext:runtime/40_process.js:388:10)
[4:43:43 PM]     at Command.output (ext:runtime/40_process.js:463:12)
[4:43:43 PM]     at open (gauntlet:module?vendor:50:45)
[4:43:43 PM]     at onClick (gauntlet:module?shared:809:15)
[4:43:43 PM]     at onClick (gauntlet:module?shared:824:51)
[4:43:43 PM]     at handleEvent (ext:gauntlet/core.js:171:21)
[4:43:43 PM]     at runPluginLoop (ext:gauntlet/core.js:227:21)
[4:43:43 PM]     at eventLoopTick (ext:core/01_core.js:175:7)
[4:43:43 PM]     at async gauntlet:init:8:5
[4:43:43 PM]   },
[4:43:43 PM]   reason: Error: Requires run access to "xdg-open", run again with the --allow-run flag
[4:43:43 PM]     at spawnChildInner (ext:runtime/40_process.js:184:17)
[4:43:43 PM]     at spawn (ext:runtime/40_process.js:388:10)
[4:43:43 PM]     at Command.output (ext:runtime/40_process.js:463:12)
[4:43:43 PM]     at open (gauntlet:module?vendor:50:45)
[4:43:43 PM]     at onClick (gauntlet:module?shared:809:15)
[4:43:43 PM]     at onClick (gauntlet:module?shared:824:51)
[4:43:43 PM]     at handleEvent (ext:gauntlet/core.js:171:21)
[4:43:43 PM]     at runPluginLoop (ext:gauntlet/core.js:227:21)
[4:43:43 PM]     at eventLoopTick (ext:core/01_core.js:175:7)
[4:43:43 PM]     at async gauntlet:init:8:5
[4:43:43 PM] }
```

**Comment by Exidex** [comment]
This turned out to be interesting.

First there was an issue with values in `permissions.exec.command` not being resolved properly. This is fixed in: dd12028e15a48e39a514a23fddc5cb6902e83210

This has 2 caveats:
1. If PATH env var was changed after Gauntlet was started, new value will not be detected until after Gauntlet restart. This is general limitation of unix-like systems
2. If command on PATH was installed after plugin was started it will also not be detected and permission error will be thrown. This is currently a restriction in Deno, because it requires values for exec permissions to be resolved at runtime startup

And then there is an issue with LD_LIBRARY_PATH.

If any `LD_*` or `DYLD_*` environment variables are set, Deno (rightfully so) rejects any command execution unless global permission is given to run all and any executables on system (context: https://github.com/denoland/deno/issues/26839 and https://github.com/denoland/deno/issues/26843). But Gauntlet doesn't provide a way to set this global permission (and I am hesitant to allow it for the same reason).

So currently if executing binaries with `Deno.Command` you have to set `LD_LIBRARY_PATH` to empty value `""` (currently [@opensrc/deno-open](https://jsr.io/@opensrc/deno-open) doesn't allow for that but it should be fairly straight forward to use `xdg-open` directly)

**Comment by Exidex** [comment]
@schradert I see that nix package uses LD_LIBRARY_PATH, would setting it to empty string in plugin be problematic?

**Comment by schradert** [comment]
> @schradert I see that nix package uses LD_LIBRARY_PATH, would setting it to empty string in plugin be problematic?

Not for users I don't think because the actual package doesn't use `LD_LIBRARY_PATH`, rather `RPATH` headers injected by `patchelf`, but [this](https://github.com/project-gauntlet/gauntlet/blob/63a54d1d18569780cf340c403dc861c54055e05b/nix/default.nix#L23) affects developing on Gauntlet itself, so I guess it might break `dev_plugin` for contributors using Nix. Happy to test this out and report back later. If it's a problem, maybe a different mechanism makes sense in the devShell block like `DT_RPATH`.

**Comment by Exidex** [comment]
What about plugins that depend on some CLI command that is not in dependencies of nix package?

**Comment by schradert** [comment]
With the change I made in a new PR (unrelated to this current issue but still necessary), I was able to run gauntlet in development on NixOS, as well as the gauntlet dev server on the tailwindcss branch of cswimr's plugin repo. That means `LD_LIBRARY_PATH` is still explicitly appended to in the devShell. The links opened successfully because `xdg-open` is installed globally and this installation path is available to gauntlet when run. Just like with other distros, the simplest solution would be to install the dependency globally, and this is definitely the recommended way to handle `xdg-open` on NixOS and non-NixOS systems with home-manager. However, if a plugin needs a runtime dependency not provided by the gauntlet derivation and Nix users don't want to install it globally, the solution would be to package it alongside the plugin using Nix and expose this to gauntlet somehow. There are probably a few different ways to do accomplish this, but I need to understand better what happens when a plugin is added and also if there is a mechanism to add plugins without the server running.

**Comment by Exidex** [comment]
I am not sure I follow, in my tests if LD_LIBRARY_PATH is present, Deno will throw exception. Is it somehow not an issue?

**Comment by Exidex** [comment]
[v13](https://github.com/project-gauntlet/gauntlet/releases/tag/v13) with fix is released, so closing this.
